import Head from 'next/head'
import {PhraseList } from '@/components/module/phraseList'
import { Header } from '@/components/atoms/header'


export default function Home() {
  return (
    <>
      <Head>
        <title>Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
       <PhraseList  />

    </>
  )
}
